export { Diagram } from "./diagram";
export { Pen } from "./pen";
export { Message } from "./message";
export { Flag } from "./flag";
export { Comfort } from "./comfort";
export { Mark } from "./mark";
export { MarkGrey } from "./mark-grey";
export { Standart } from "./standart";
export { Premium } from "./premium";
export { Plus } from "./plus";
export { Minus } from "./minus";
export { Instagram } from "./instagram";
export { Telegram } from "./telegram";
export { Twitter } from "./twitter";
export { Vk } from "./vk";
export { Youtube } from "./youtube";
export { Modal } from "./modal";
export { Portal } from "./portal";
export { Close } from "./close";
export { Warning } from "./warning";
export { Subscription } from "./close copy";

